### ISSUE TITLE
White overflow on the bottom of page when display exceeds certain size

### ISSUE THREAD

**Issue by kevinyjiang** [kevinyjiang/kevinyjiang.github.io#1]
Scroll down about 15 pixels

**Comment by devadvance** [comment]
Fairly certain that this is caused by this code:
```
.preview {
	position: absolute;
	width: 100%;
	top: 50%;
	left: 50%;
	transform: translate(-50%, -50%);
}
```
When you only set width, the height is changed to keep the aspect ratio. This means that when the boxes are wider than 1:1 ratio, the height is too large.

Easy fix might just be removing `width: 100%;`

**Comment by kevinyjiang** [comment]
fixed by setting `overflow: hidden` on .wrapper
