### ISSUE TITLE
Rotating and then rotating back to original orientation on mobile causes browser to zoom in

### ISSUE THREAD

**Issue by kevinyjiang** [kevinyjiang/kevinyjiang.github.io#5]

**Comment by devadvance** [comment]
Doesn't happen on Chrome on Android. Might be Safari specific.

Might want to try setting a viewport value, like this:
```
<meta name="viewport" content="width=device-width, initial-scale=1.0">
```

See more: https://www.w3schools.com/Css/css_rwd_viewport.asp
